
services:
  data-warehouse:
    image: clickhouse/clickhouse-server

    ports:
      - 8123:8123

    # volumes:
      # - ./clickhouse:/var/lib/clickhouse
      # - ./clickhouse-server:/etc/clickhouse-server

    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin
      - CLICKHOUSE_DB=dev

  data-lake:
    image: quay.io/minio/minio

    ports:
      - 9000:9000
      - 9001:9001

    command: server /data --console-address ":9001"

    volumes:
      - ./minio_data:/data

    environment:
      - MINIO_ROOT_USER=ROOTNAME
      - MINIO_ROOT_PASSWORD=CHANGEME123
