
services:
  data-warehouse:
    image: clickhouse/clickhouse-server

    ports:
      - 8123:8123

    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin

    volumes:
      - clickhouse:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server

  data-lake:
    image: quay.io/minio/minio

    ports:
      - 9000:9000
      - 9001:9001

    command: server /data --console-address ":9001"

    volumes:
      - minio-data:/data

    environment:
      - MINIO_ROOT_USER=ROOTNAME
      - MINIO_ROOT_PASSWORD=CHANGEME123

  graph:
    image: neo4j
      
    volumes:
      - neo4j-data:/data

    ports:
      - 7474:7474
      - 7687:7687

  etls:
    build: ./etls

volumes:
  clickhouse:
    external: true
  clickhouse-logs:
    external: true
  neo4j-data:
    external: true
  minio-data:
    external: true
