service: despesasgoverno

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  profile: etl
  deploymentMethod: direct
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: "arn:aws:s3:::linker-etl/raw/despesas_governo_federal/*"
    - Effect: "Allow"
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: "arn:aws:s3:::linker-etl/processed/despesas_governo_federal/*"
    - Effect: "Allow"
      Action:
        - secretsmanager:GetSecretValue
      Resource: "*"
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      etlimage:
        path: ./
        file: Dockerfile

functions:

  etl:
    description: performs the etl pipeline for despesas governo federal
    image:
      name: etlimage
    timeout: 600
    events:
      - schedule: cron(5 0 * * ? *)
