version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bnmp-cookie-machine"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rn60vb3gp2xl"
s3_prefix = "bnmp-cookie-machine"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
