CREATE DATABASE ibama;

CREATE TABLE ibama.termo_embargo (
    seq_tad VARCHAR,
    des_status_formulario VARCHAR,
    des_status_formulario_aie VARCHAR,
    sit_cancelado VARCHAR,
    num_tad VARCHAR,
    ser_tad VARCHAR,
    cod_substituicao VARCHAR,
    dat_embargo VARCHAR,
    dat_impressao VARCHAR,
    forma_entrega VARCHAR,
    num_pessoa_embargo VARCHAR,
    nome_embargado VARCHAR,
    cpf_cnpj_embargado VARCHAR,
    num_processo VARCHAR,
    des_tad VARCHAR,
    cod_municipio VARCHAR,
    municipio VARCHAR,
    uf VARCHAR,
    des_localizacao VARCHAR,
    num_longitude_tad VARCHAR,
    num_latitude_tad VARCHAR,
    deter_prodes VARCHAR,
    id_poligono VARCHAR,
    embarga_poligono VARCHAR,
    qtd_area_embargada VARCHAR,
    nome_imovel VARCHAR,
    tipo_area VARCHAR,
    geom_area_embargada VARCHAR,
    dat_ult_alter_geom VARCHAR,
    unid_apresentacao VARCHAR,
    unid_controle VARCHAR,
    sit_desembargo VARCHAR,
    tipo_desembargo VARCHAR,
    dat_desembargo VARCHAR,
    des_desembargo VARCHAR,
    seq_auto_infracao VARCHAR,
    num_auto_infracao VARCHAR,
    seq_notificacao VARCHAR,
    seq_acao_fiscalizatoria VARCHAR,
    cd_acao_fiscalizatoria VARCHAR,
    operacao VARCHAR,
    seq_ordem_fiscalizacao VARCHAR,
    ordem_fiscalizacao VARCHAR,
    unid_ordenadora VARCHAR,
    seq_solicitacao_recurso VARCHAR,
    solicitacao_recurso VARCHAR,
    operacao_sol_recurso VARCHAR,
    dat_ult_alteracao VARCHAR,
    tipo_alteracao VARCHAR,
    justificativa_alteracao VARCHAR,
    ultima_atualizacao_relatorio VARCHAR
    )
    ENGINE = MergeTree()
    ORDER BY (cpf_cnpj_embargado);